name: my_learning
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  toastification: ^3.0.3
  device_preview: ^1.3.1
  get: ^4.7.2
  flutter_slidable: ^4.0.3
  mask_text_input_formatter: ^2.9.0
  google_fonts: ^6.3.2
  carousel_slider: ^5.1.1
  loading_animation_widget: ^1.3.0
  font_awesome_flutter:
  animated_text_kit: ^4.3.0
  url_launcher: ^6.3.2
  audioplayers: ^6.5.1
  pushable_button: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


